### ISSUE TITLE
Missing 'model' package in the app-kotlin template directory.

### ISSUE THREAD

**Issue by codebymikey** [cavarzan/generator-android-hipster#15] opened 2016-03-12 22:08 UTC
With the following configuration:

```
? What are the name of your app? SampleApp
? What is the package name of the app? io.sampleapp
? What language would you like to use?  Kotlin
? What Image Lib would you like to use?  Picasso
? What MVP do you want to use?  Embeed MVP (No Lib)
? Use ButterKnife?  Yes
? Would you like to use EventBus? Yes
? Would you like to use calligraphy for custom fonts? Yes
? Would you like to use Joda Time? Yes
? Would you like to use MixPanel? No
? Would you like to use Joda Money? No
? Would you like to use Timber for logs? Yes
? Would you like to use PrintView for icon font? Yes
? Would you like to use Stetho for Network Monitoring? Yes
? Would you like to use PaperParcel? Yes
? What Android SDK will you be targeting? 23
? What is the minimum Android SDK you wish to support? 15
```

I receive the following error message:

```
events.js:141                                                                                                                                                           
      throw er; // Unhandled 'error' event                                                                                                                              
      ^                                                                                                                                                                 
 AssertionError: Trying to copy from a source that does not exist: C:\Users\Mikey\AppData\Roaming\npm\node_modules\generator-android-hipster\app\templates\app-kotlin\sr
c\main\java\model                                                                                                                                                       
    at EditionInterface.exports._copySingle (C:\Users\Mikey\AppData\Roaming\npm\node_modules\generator-android-hipster\node_modules\mem-fs-editor\lib\actions\copy.js:45
:3)                                                                                                                                                                     
    at EditionInterface.exports.copy (C:\Users\Mikey\AppData\Roaming\npm\node_modules\generator-android-hipster\node_modules\mem-fs-editor\lib\actions\copy.js:23:17)   
    at EditionInterface.module.exports [as copyTpl] (C:\Users\Mikey\AppData\Roaming\npm\node_modules\generator-android-hipster\node_modules\mem-fs-editor\lib\actions\co
py-tpl.js:12:8)                                                                                                                                                         
    at template (C:\Users\Mikey\AppData\Roaming\npm\node_modules\generator-android-hipster\node_modules\yeoman-generator\lib\actions\actions.js:134:11)                 
    at module.exports.AppGenerator.extend.writing.app (C:\Users\Mikey\AppData\Roaming\npm\node_modules\generator-android-hipster\app\index.js:384:18)                   
    at C:\Users\Mikey\AppData\Roaming\npm\node_modules\generator-android-hipster\node_modules\yeoman-generator\lib\base.js:430:16                                       
    at processImmediate [as _immediateCallback] (timers.js:383:17)                                                                                                      
```

It seems the kotlin template directory is missing its model package.
You should probably run a diff of the `app-kotlin` and `app-java` directories to ensure that they all contain the equivalent number of files.

**Comment by codebymikey** [comment] 2016-03-13 00:13
The generated kotlin code doesn't seem to work out of the box either - it's missing a couple of method overrides and declarations.

**Comment by cavarzan** [comment] 2016-03-14 13:34
@codebymikey can you check your version? it's the latest one?
I will create using your configuration and check what happens, until tomorrow I'll update a fix.

**Comment by codebymikey** [comment] 2016-03-15 23:44
Yes, I believe so.

As you can see below, the 'model' package is [missing](https://github.com/cavarzan/generator-android-hipster/tree/master/app/templates/app-kotlin/src/main/java) in the app-kotlin folder, but [present](https://github.com/cavarzan/generator-android-hipster/tree/master/app/templates/app-java/src/main/java) in the app-java one.

**Comment by cavarzan** [comment] 2016-03-17 02:45
@codebymikey the model folder don't make any difference right now because it's empty, and npm just ignore it, in earlier versions it was used to create default models, but this was migrated to a separated task.
I create a package-info to solve, but the main thing is that your plugin is out of date, based on the questions and the error. I fixed some issues here that I found but I need to run some tests before publish and I can't reproduce with the latest version.
In this case you need to run `npm update -g generator-android-hipster`. Sometimes (I don't know when exactly) npm ignore the update, so it can be fixed uninstalling (`npm uninstall -g generator-android-hipster`) and install it again.
I hope to publish the version 0.2.4 this friday, I just want to make sure that everything is  working fine. I will notify you here and we can test it again.

**Comment by cavarzan** [comment] 2016-03-22 19:26
Fixed in latest commit. v 0.2.4.

**Closed as completed by cavarzan** 2016-03-22 19:26 UTC
Labels: bug
